# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tugas_UTS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Management Book and Film - Ida Ayu Vinaya Anindya (F1D022124)")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 491, 541))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.tableWidget = QtWidgets.QTableWidget()
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setHorizontalHeaderLabels(["Title", "Type", "Director/Author", "Year", "Rate"])
        self.horizontalLayout.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton("Add", self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 10, 91, 21))
        self.lineEdit.setPlaceholderText("Search")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(698, 10, 91, 21))
        self.comboBox.addItem("") 
        self.comboBox.addItem("Terbaru")
        self.comboBox.addItem("Film's")
        self.comboBox.addItem("Book's")
        self.label = QtWidgets.QLabel("Title :", self.centralwidget)
        self.label.setGeometry(QtCore.QRect(510, 50, 47, 13))
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(510, 70, 281, 31))
        self.label_2 = QtWidgets.QLabel("Type :", self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 120, 47, 13))
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(510, 140, 281, 31))
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("Book")
        self.comboBox_2.addItem("Film")

        self.label_3 = QtWidgets.QLabel("Director/ Author :", self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(510, 190, 101, 21))
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(510, 210, 281, 31))

        self.label_4 = QtWidgets.QLabel("Year :", self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 260, 47, 13))
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(510, 280, 281, 31))
        self.label_6 = QtWidgets.QLabel("Rate :", self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(510, 330, 47, 13))
        self.checkBox = QtWidgets.QCheckBox("Bagus", self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(510, 350, 70, 17))
        self.checkBox_2 = QtWidgets.QCheckBox("Biasa Saja", self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(600, 350, 90, 17))
        self.checkBox_3 = QtWidgets.QCheckBox("Buruk", self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(720, 350, 70, 17))
        self.label_5 = QtWidgets.QLabel("Sinopsis :", self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 380, 60, 13))
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(510, 400, 281, 101))
        self.pushButton_2 = QtWidgets.QPushButton("Save", self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(720, 520, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

       
        self.data_list = []
        self.pushButton.clicked.connect(self.add_data)
        self.pushButton_2.clicked.connect(self.save_data)
        self.lineEdit.textChanged.connect(self.search_data)
        self.comboBox.currentTextChanged.connect(self.filter_data)

       
        self.tableWidget.setStyleSheet("QTableWidget {background-color: #f2f2f2; font-size: 14px;}")
        self.pushButton.setStyleSheet("QPushButton {background-color: #4CAF50; color: white; border-radius: 5px;}")
        self.pushButton_2.setStyleSheet("QPushButton {background-color: #4CAF50; color: white; border-radius: 5px;}")
        
    def save_data(self):
        title = self.textEdit.toPlainText().strip()
        tipe = self.comboBox_2.currentText()
        author = self.textEdit_2.toPlainText().strip()
        year = self.textEdit_3.toPlainText().strip()
        rate = ""
        if self.checkBox.isChecked():
            rate = "Bagus"
        elif self.checkBox_2.isChecked():
            rate = "Biasa Saja"
        elif self.checkBox_3.isChecked():
            rate = "Buruk"

        if title and tipe and author and year:
            item = {
                "title": title,
                "type": tipe,
                "author": author,
                "year": year,
                "rate": rate,
            }
            self.data_list.append(item)
            self.show_data(self.data_list)
            self.add_data() 
            
    def add_data(self):
        self.textEdit.clear()
        self.comboBox_2.setCurrentIndex(0)
        self.textEdit_2.clear()
        self.textEdit_3.clear()
        self.textEdit_4.clear()
        self.checkBox.setChecked(False)
        self.checkBox_2.setChecked(False)
        self.checkBox_3.setChecked(False)

    def show_data(self, data):
        self.tableWidget.setRowCount(0)
        for row_num, item in enumerate(data):
            self.tableWidget.insertRow(row_num)
            self.tableWidget.setItem(row_num, 0, QtWidgets.QTableWidgetItem(item["title"]))
            self.tableWidget.setItem(row_num, 1, QtWidgets.QTableWidgetItem(item["type"]))
            self.tableWidget.setItem(row_num, 2, QtWidgets.QTableWidgetItem(item["author"]))
            self.tableWidget.setItem(row_num, 3, QtWidgets.QTableWidgetItem(item["year"]))
            self.tableWidget.setItem(row_num, 4, QtWidgets.QTableWidgetItem(item["rate"]))

    def search_data(self):
        keyword = self.lineEdit.text().lower()
        filtered = [item for item in self.data_list if keyword in item["title"].lower()]
        self.show_data(filtered)

    def filter_data(self, selected):
        if selected == "Terbaru":
            sorted_data = sorted(self.data_list, key=lambda x: x["year"], reverse=True)
        elif selected == "Film's":
            sorted_data = [i for i in self.data_list if i["type"] == "Film"][:5]
        elif selected == "Book's":
            sorted_data = [i for i in self.data_list if i["type"] == "Book"][:5]
        else:
            sorted_data = self.data_list
        self.show_data(sorted_data)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
